"""empty message

Revision ID: 04c9200aad93
Revises: 13cb9836a31e
Create Date: 2023-09-10 05:39:24.175006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c9200aad93'
down_revision = '13cb9836a31e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
