"""empty message

Revision ID: 074528ad2943
Revises: 99650f41ed27
Create Date: 2023-09-10 05:59:53.303197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074528ad2943'
down_revision = '99650f41ed27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
