"""empty message

Revision ID: 0a15dfe5de17
Revises: 8c71b5907246
Create Date: 2023-09-18 18:04:21.788707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a15dfe5de17'
down_revision = '8c71b5907246'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
