"""empty message

Revision ID: 0af0b86c193e
Revises: 0a15dfe5de17
Create Date: 2023-09-18 18:15:46.444572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af0b86c193e'
down_revision = '0a15dfe5de17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
