"""empty message

Revision ID: 40d53d77d7af
Revises: 074528ad2943
Create Date: 2023-09-18 17:57:36.966811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d53d77d7af'
down_revision = '074528ad2943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
