"""empty message

Revision ID: 41d4e4a3296d
Revises: 8a4a1983b92e
Create Date: 2023-09-18 18:52:10.672369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d4e4a3296d'
down_revision = '8a4a1983b92e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
