"""empty message

Revision ID: 8a4a1983b92e
Revises: ab9d19657543
Create Date: 2023-09-18 18:26:59.250394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4a1983b92e'
down_revision = 'ab9d19657543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
