"""empty message

Revision ID: 8c71b5907246
Revises: 40d53d77d7af
Create Date: 2023-09-18 18:01:02.586623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c71b5907246'
down_revision = '40d53d77d7af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
