"""empty message

Revision ID: 99650f41ed27
Revises: eb7de755b050
Create Date: 2023-09-10 05:51:47.466298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99650f41ed27'
down_revision = 'eb7de755b050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
