"""empty message

Revision ID: ab9d19657543
Revises: 0af0b86c193e
Create Date: 2023-09-18 18:25:38.687646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9d19657543'
down_revision = '0af0b86c193e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
